services:
  - type: web
    name: rex-os-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false # Tells Render you will set this manually in the dashboard
      - key: NODE_ENV
        value: production
